const int strlen(const char *str);
const char *strdup(const char *str);
const int strcontains(const char *str0, const char *str1);
const int strcmp(const char *str0, const char *str1);
const char *strconcatenate(const char *str0, const char *str1);
const char *readi();
const char *read_file(const char *restrict file_name);
const int shift_mask_left(const int mask, const int i);
const int and_operation(const int number, const int mask_shifted);
const int shift_result_right(const int number, const int i);
void convert_integer_to_binary(int *restrict array, const int number, const int mask, const int architecture);
double pow(double x, double y);
int convert_binary_to_integer(int *array, int architecture);
int find_string_position(const char *buffer, const char *string, const int position);
char **strsplit_v1(const char *string, const char *spliter);